version: '3.8'

services:
  nginx:
    container_name: nginx
    image: nginx:latest
    depends_on:
      - web-app
    networks:
      - net
    volumes_from:
      - web-app
    volumes:
      - /etc/letsencrypt/live/alextecture.com/fullchain.pem:/etc/letsencrypt/live/alextecture.com/fullchain.pem
      - /etc/letsencrypt/live/alextecture.com/privkey.pem:/etc/letsencrypt/live/alextecture.com/privkey.pem
      - ./nginx.conf:/etc/nginx/nginx.conf
      - soureces:/etc/letsencrypt
      - soureces:/var/www/certbot
      - soureces:/usr/share/nginx/html
      - soureces:/data/
    ports:
      - 80:80
      - 443:443
  web-app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - soureces:/data/
volumes:
  soureces:
    driver: local
    external: true
networks:
  net:
    driver: bridge
