version: '3.7'

services:
  web-app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    ports:
      - 80:80
      - 443:443
    networks:
      - net
  certbot:
    image: certbot/certbot
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
      - ./init-letsencrypt.sh:./
    depends_on:
      - web-app
    command: /bin/sh -c "./init-letsencrypt.sh"
    networks:
      - net
networks:
  net:
    driver: bridge