version: '3.7'

services:
  nginx:
    container_name: nginx
    image: nginx:latest
    depends_on:
      - web-app
    networks:
      - net
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      # - ./ssl-options.conf:/etc/nginx/conf.d/ssl-option.conf
      - soureces:/etc/letsencrypt
      - soureces:/var/www/certbot
      - soureces:/usr/share/nginx/html
    volumes_from:
      - "web-app"
    ports:
      - 80:80
      - 443:443
  web-app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - soureces:/data/dist
  # certbot:
  #   image: certbot/certbot
  #   depends_on:
  #     - nginx
  #   container_name: certbot
  #   volumes:
  #     - soureces:/etc/letsencrypt
  #     - soureces:/var/www/html
    # command: certonly --webroot --webroot-path=/var/www/html --email alextecture@yandex.ru --agree-tos --no-eff-email --staging -d alextecture.com
volumes:
  soureces:
    external: true
networks:
  net:
    driver: bridge